import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#faf9f8",
        tertiary: "#00676b",
        "on-secondary": "#ffffff",
        "surface-tint": "#ba1b16",
        "secondary-fixed-dim": "#b8c9d3",
        "inverse-surface": "#2f3130",
        "tertiary-container": "#008287",
        "primary-fixed": "#ffdad5",
        secondary: "#506169",
        primary: "#b61814",
        "on-tertiary-fixed": "#002021",
        "on-error-container": "#93000a",
        "outline-variant": "#e4beb8",
        "surface-variant": "#e3e2e1",
        "on-background": "#1a1c1c",
        background: "#faf9f8",
        "surface-container": "#eeeeed",
        "primary-fixed-dim": "#ffb4a9",
        "inverse-on-surface": "#f1f0f0",
        outline: "#906f6b",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#80f4fa",
        "on-surface-variant": "#5b403c",
        "secondary-container": "#d1e2ec",
        "surface-container-low": "#f4f3f2",
        "on-error": "#ffffff",
        "on-primary-fixed": "#410001",
        "on-surface": "#1a1c1c",
        "on-primary-fixed-variant": "#930005",
        "tertiary-fixed-dim": "#61d8de",
        "on-primary": "#ffffff",
        "surface-container-high": "#e9e8e7",
        "error-container": "#ffdad6",
        "inverse-primary": "#ffb4a9",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#fffbff",
        "primary-container": "#da342a",
        "on-tertiary-container": "#f3ffff",
        "secondary-fixed": "#d4e5ef",
        "on-secondary-fixed-variant": "#394951",
        "surface-bright": "#faf9f8",
        "on-secondary-fixed": "#0d1e25",
        "on-secondary-container": "#55656d",
        "surface-container-highest": "#e3e2e1",
        "surface-dim": "#dadad9",
        "on-tertiary-fixed-variant": "#004f52",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
